### ISSUE TITLE
URL '/v3/apps?space_guids=<GUID>&per_page=50&page=1' is malformed

### ISSUE THREAD

**Issue by agiguere** [SAP-samples/automation-pilot-examples#120]
**Describe the bug**
I trigger the command to mass stop all CF apps in a space

and I got the following errors:
URL '/v3/apps?space_guids=<GUID>&per_page=50&page=1' is malformed

where GUID is my space guide

**To Reproduce**
I imported your catalog and pass all parameters, I am using a technical users from SAP Identity Authentication

**Expected behavior**

**Screenshots**

**Tenant (please complete the following information):**
 - Automation Pilot Region: us30
 - Execution ID: T000269R3-0000001732232956259-0-1

**Additional context**

**Comment by kloyan** [comment]
Hi @agiguere. Please use `cf-us30` as your region instead of `us30`. You can see the list of all valid BTP regions [here](https://help.sap.com/docs/btp/sap-business-technology-platform/regions-and-api-endpoints-available-for-cloud-foundry-environment) (column _Technical Key_)

**Comment by agiguere** [comment]
@kloyan this is the region of my subaccount where Automation Pilot is, the region I am passing as input key is CF-10, I also tried CF-10-001 (extension)

the CF apps I want to stop on an another subaccount (cf-us10-001)

could it be related to a restriction on the free service plan of Automation Pilot

in the SA that I have Automation Pilot, do I have to activate others services, enable Cloud Foundry?

thanks

**Comment by agiguere** [comment]
<img width="1708" alt="Screenshot 2024-11-22 at 7 54 18 AM" src="https://github.com/user-attachments/assets/0d16f544-4354-4f1f-9a50-7591a2d63283">

**Comment by kloyan** [comment]
Hi @agiguere. Could you please screenshot the input values (click the _Show_ button under _Input_). You need to use the exact technical key of your region - _cf-us10-001_ or _cf-us30_ (lowercase)

**Comment by agiguere** [comment]
<img width="1091" alt="Screenshot 2024-11-22 at 8 01 51 AM" src="https://github.com/user-attachments/assets/2f9922f9-f382-435f-b836-4167bf5e4cfe">

**Comment by agiguere** [comment]
@kloyan it works, I added the -001

**Comment by agiguere** [comment]
@kloyan I checked both commands MassStartCfAppsInOrg & MassStartCfAppsInSpace

MassStartCfAppsInOrg has an additional filter step on spaces

what we need is a filter on CF app name to avoid starting deployer apps

when you push a CAP app to CF, a db-deployer app is started and stopped after db artifact are uploaded to HANA Cloud

so when starting CF apps with the command, I don't want to starts these db-deployer apps, I need to filter on them

any idea how to do that?

thanks

**Comment by kloyan** [comment]
Hi @agiguere. You can adapt the commands to easily exclusion by app name. You can use the exclusion by space as an example as the pattern is quite similar.

If you would like us to extend the already available example, please create a separate feature request in this repository.
