### ISSUE TITLE
Mass Start CF Apps In Org or Space new filter for app name

### ISSUE THREAD

**Issue by agiguere** [SAP-samples/automation-pilot-examples#122]
This is a feature request to add a filter on the CF app names on both MassStartCfAppsInOrg & MassStartCfAppsInSpace

Actually, there should be a hardcoded filter on DB Deployer app name (to exlucde them), if the commands tried to start a CF DB Deployer app, it will failed and the script also will failed

DB Deployer apps are only used by HDI when deploying a CAP app then after they are stopped

thanks
Alex

**Comment by agiguere** [comment]
is there a way to speed up these enhancements, should a create an incident via me.sap.com?

this is the proof that nobody in the world is using your repo, starting a db deployer will make the script failed

and all CAP apps or Fiori apps have db deployer modules

alex

**Comment by kloyan** [comment]
Hi @agiguere,

Open source projects greatly benefit from community contributions, and you're welcome to make enhancements to fit your specific scenarios. If you're interested, you can fork the repository and submit a pull request with your improvements. More information is also available in the [README](https://github.com/SAP-samples/automation-pilot-examples?tab=readme-ov-file#contributing).

You don't need to create an incident for open-source projects, especially when the repository is meant to provide samples that don't cover all use cases. While CAP and Fiori are popular, they aren't used by everyone.

I'll try to look into your issues sometime next week if you decide not to contribute. However, it would be more motivating to assist if we maintain a collaborative and respectful tone.

Kaloyan

**Comment by agiguere** [comment]
Sorry, I did not mean to offend

SAP itself references this repo on some blogs, so we think that SAP could do better with this service (SAP Automation Pilot), like the readme said, having apps & db up & running on dev & test subaccounts could be pricy

we would like to see some support for Opening & Closing SAP HANA Cloud database instances on the multi-environment, providing filtering options for starting / closing CF apps by SAP and not rely on open-source

I would be happy to help, it’s just that I don’t know these very well commands and we can’t use JS

on the MassStartCfAppsInOrg example, the filtering of spaces is done by a subtraction of two arrays

I don’t think we should follow this design for filtering apps, I think it would be better to label the apps that could be started & closed, or the inverse, labelling the apps that should be excluded

alex

**Comment by kloyan** [comment]
Hi @agiguere,

Thank you for the suggestion about using labels. I've updated the 'Mass Stop/Start CF Apps' example to allow you to specify a set of labels. Apps with any of them will be ignored.

Please test it and let me know your feedback.

**Comment by agiguere** [comment]
@kloyan thanks it works

quick update, there is a mistake in the documentation for the CLI usage

cf set-label **app** my-app environment=production

you have to add app in front of my-app

as for the manifest, is there a way to do it at the MTA descriptor file level instead, it would be much easier

**Comment by agiguere** [comment]
@kloyan it does not work when scheduling an execution, the password field on the parameter screen is gray out and not editable, any idea how to fix this?

thanks

**Comment by agiguere** [comment]
<img width="920" alt="Image" src="https://github.com/user-attachments/assets/f3c6e32f-8733-48b0-97ad-77d77e28883f" />

**Comment by kloyan** [comment]
@agiguere Sensitive data should not be hardcoded. Instead, they should be referred to using **Inputs**.

How to create an **_Input_**:

1. Navigate to the **_Inputs_** section.
2. Click on **_Create_**.
3. Choose a catalog and assign a name of your choice.
4. Add a new sensitive key named **_password_**.
5. Enter your password as the value.

![Input Creation Image](https://github.com/user-attachments/assets/8c6886bd-281f-4fc1-b690-645697f4814a)

How to attach an _**Input**_ to a Scheduled Execution:

1. During the first stage of the creation wizard, select your desired input from the dropdown menu.
2. All corresponding values will be automatically derived from the selected input.

![Scheduled Execution Image](https://github.com/user-attachments/assets/074a4655-b96b-4fa0-8bfa-b481a3cff43e)
![Execution Example Image](https://github.com/user-attachments/assets/f4228726-4964-4cec-97be-1a9bd1ca252e)

**Comment by kloyan** [comment]
@agiguere I fixed the `cf set-label` usage with #139. Thanks for mentioning it.

MTA does not support setting the application labels as of now. You can contact the MTA team if this is an important feature for you.

**Comment by agiguere** [comment]
@kloyan thanks

regarding the password being grayed out, it's now ok by configuring an input as you mentioned, however, the scheduled execution of AP is very limited, there are no custom schedules, not possible to execute only in the weeks and exclude weekends, skip days etc ... should I propose this enhancement via me.sap.com as an incident case or via the influence site?

As for the CF app label, labelling via the CLI is an additional step for every new MTA that we deploy, we will have to establish some governance to make sure developers don't forget that step, inside the MTA would have been much easier and could have been validated via code review or PR ... since CF is open source, if CF doesn't even support it, I don't think SAP can do something about it, however, if it's not, then maybe I can request that enhancement via the influence customer site, what do you think?

thanks

**Comment by kloyan** [comment]
@agiguere 

Automation Pilot supports various scheduling options: Hourly, Daily, Weekly, Monthly, and Yearly. For instance, if you choose the Weekly option, you can configure your automation to run only on weekdays (Monday to Friday) and skip execution on weekends.

<img width="1167" alt="Image" src="https://github.com/user-attachments/assets/f8ffb3d2-a595-4c2f-8a2c-7c6aac5ea241" />

<img width="1160" alt="Image" src="https://github.com/user-attachments/assets/ce8e4db8-72a4-4925-be04-59be207cf54e" />

Does this work for you?

Regarding CF app labels, you can define them using standard CF app manifests, as detailed in the Cloud Foundry documentation [here](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#metadata). However, MTA currently does not support this functionality, as noted in [Unsupported Cloud Foundry Features](https://help.sap.com/docs/btp/sap-business-technology-platform/multitarget-applications-in-cloud-foundry-environment#prerequisites-and-restrictions). Please contact the MTA team for more information on the feasibility of this request.

**Comment by agiguere** [comment]
@kloyan thanks, sure I will tried to contact the MTA team for this feasibility 

for the scheduling, I did not check the detail of the weekly options because I was under the impression that it was for once a week, let me try that one!

**Comment by agiguere** [comment]
@kloyan FYI, I created 2 feature requests, please feel free to vote for it

https://influence.sap.com/sap/ino/#/idea/338399
https://influence.sap.com/sap/ino/#/idea/338400

thanks for the support
