### ISSUE TITLE
Mass Stop/Start HANA Cloud Databases requirement regarding Service Manager not clear

### ISSUE THREAD

**Issue by agiguere** [SAP-samples/automation-pilot-examples#123]
The requirements regarding using SAP Service Manager with Mass Stop/Start HANA Cloud Databases are not clear

https://github.com/SAP-samples/automation-pilot-examples/tree/main/mass-stop-start-hana-cloud

The instance for SAP Service Manager should be created on the Subaccount of Automation Pilot or the Subaccount of HANA Cloud?

HANA cloud is not anymore deploy at CF space level

Not sure to understand how the service key name (example my-key) could be accessible through the automation pilot and communicate with HANA cloud into another subaccount?

thanks

**Comment by kloyan** [comment]
Hi @agiguere,

The Service Manager instance should be created within the subaccount that hosts your HANA Cloud databases. Once you have created a service key for this instance, you need to provide it as an input for the Automation Pilot command. Automation Pilot will use the service key to dynamically discover all the HANA Cloud databases in the subaccount.

**Comment by agiguere** [comment]
@kloyan thanks, I tested the close command for SAP HANA Cloud, particularly the command for listing the instance and it does not work

it connected successfully to the subaccount but it can't find hana cloud, I created a label both at the app level and service instance, if I remove the label selector "service eq 'hana-cloud' then some services are returned

alex

**Comment by agiguere** [comment]
@kloyan I found the bug (it's in your side), the origin key for SAP HANA Cloud is not cloudfoundry but SAPCP, I changed the fieldselector filter on the list instance and it works now, please correct

<img width="221" alt="Screenshot 2024-12-09 at 8 12 30 AM" src="https://github.com/user-attachments/assets/4d89663f-6528-4236-a32a-159fddb57eb6">
