### ISSUE TITLE
Example check-cf-space-quota-utilization does not work with custom IdP

### ISSUE THREAD

**Issue by AlexP-J** [SAP-samples/automation-pilot-examples#133]
**Affected Example**
check-cf-space-quota-utilization

**Describe the bug**
The example does not work with a custom IdP. 
If input key identityProvider is different from default sap.ids authentication will fail as custom IdP is not consequently used in all executor steps. 

**To Reproduce**
1. Import example catalog from check-cf-space-quota-utilization to Automation Pilot Tenant
2. Create input with all mandatory input keys and with optional input key identityProvider (where value points to a custom IdP). 
3. Execute command
4. Authentication fails already in first step though user and password are correct. 

**Expected behavior**
Example is supposed to work with custom IdP. There is an optional input key identityProvider. 
This input key is neither used in executor getCfOauthToken nor in executor calculateSpaceMemory. 

**Screenshots**

**Tenant (please complete the following information):**
 - Automation Pilot Region: cf-eu10
 - Execution ID  T000288R4-0000001734359881107-1-1 (failed executor getCfOauthToken) and T000288R4-0000001734360340894-0-1 ( failed executor calculateSpaceMemory after fixing first executor)

**Additional context**
Replacing original input parameter `tokenUrl` in executor getCFOauthgToken by
`$(.regionData.baseUaaUrl)/oauth/token?login_hint=%7B%22origin%22:%22$(.execution.input.identityProvider)%22%7D `
and original input parameter `defaultCfCredentials` in executor calculateSpaceMemory by 
`{"user": "$(.execution.input.user)", "password": "$(.execution.input.password | toEscapedJson)", "resourceGroup":"$(.execution.input.spaceId)", "region": "$(.execution.input.region)", "subAccount": "$(.getCfOrg.output.body | toObject | .guid)", "identityProvider": "$(.execution.input.identityProvider)"}`
fixed the issue.

**Comment by kloyan** [comment]
Hi @AlexP-J,

The issue should be resolved. Please test it on our side as well.

**Comment by AlexP-J** [comment]
I could test it successfully using a custom IdP. Thanks!
